from tkinter import *
import calendar
guiscreen = Tk()
guiscreen.title("Calender")
guiscreen.geometry("600x600")
guiscreen.config(background = "ghost white")
def showcalender():
    calenderscreen = Tk()
    calenderscreen.title("Calender")
    calenderscreen.geometry("600x600")
    calenderscreen.config(background = "ghost white")
    content= year_entry.get()
    cal_year= int(content)
    cal_content= calendar.calendar(cal_year)
    cal_= Label(calenderscreen,text= cal_content, bg ="gray98", fg = "gray15", font =("Arial",20,"italic",))
    cal_.place(x=100,y=100)
    calenderscreen.mainloop()
Calender= Label(guiscreen,text= "Calender", bg ="gray98", fg = "gray15", font =("Arial",45,"italic",))
EnterText= Label(guiscreen,text="Enter Year" ,bg ="green2", fg = "gray15",font=("Arial" ,45,"italic",))
submit=Button(guiscreen,text="Submit",bg="green2",font=("Arial",45,"italic",),command=showcalender)
exit=Button(guiscreen,text="Exit",bg="red2",font=("Arial",45,"italic",))
exit.place(x=100,y=500,)
submit.place(x=100,y=350,)
Calender.place(x=100,y=100,)
EnterText.place(x=100,y=250,)
year_entry=Entry(guiscreen)
year_entry.place(x=300,y=300,)
guiscreen.mainloop()