from tkinter import*
import rockpaperscissors
guiscreen=Tk()
guiscreen.config(background="gray57")
guiscreen.geometry("800x800")
guiscreen.title("Rock Paper Scissors")
title=Label(text="Rock Paper Scissors",fg="gray2",bg="gray57",font=("Arial",25,"italic"))
title.place(x=300,y=50)
title2=Label(text="Press Button to start",fg="gray2",bg="gray57",font=("Arial",25,"italic"))
title2.place(x=300,y=100)
title3=Label(text="Your Options:",fg="gray2",bg="gray57",font=("Arial",25,"italic"))
title3.place(x=150,y=200)
title4=Label(text="Score:",fg="gray2",bg="gray57",font=("Arial",25,"italic"))
title4.place(x=150,y=300)
B1=Button(guiscreen,text="Rock")
B2=Button(guiscreen,text="Paper")
B3=Button(guiscreen,text="Scissors")
B1.place(x=400,y=200)
B2.place(x=500,y=200)
B3.place(x=600,y=200)
guiscreen.mainloop()
